name: Executar Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 6 * * 5'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12.1'

      - name: Executar script Python
        run: python scripts/meu_script.py
